import { fileURLToPath, URL } from 'node:url';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// This repo publishes its GitHub Pages output (index.html, assets/, icons)
// straight into the repository root alongside the source, so the Vite
// entry template lives at app.html instead of index.html — the latter is
// generated by `npm run deploy` and should never be hand-edited.
// The repo root also holds the published index.html (with hashed asset
// paths from the last build) so GitHub Pages has something to serve.
// If the dev server is ever asked for it — a stale browser tab, a typed
// URL — redirect to app.html instead of letting Vite try to transform a
// production HTML file that references bundles the dev server doesn't have.
const redirectStaleIndexToDevEntry = {
    name: 'redirect-stale-index-to-dev-entry',
    configureServer(server) {
        return () => {
            server.middlewares.use((req, res, next) => {
                if (req.url === '/' || req.url === '/index.html') {
                    res.statusCode = 302;
                    res.setHeader('Location', '/worldheat-tracker/app.html');
                    res.end();
                    return;
                }
                next();
            });
        };
    },
};

export default defineConfig({
    base: '/worldheat-tracker/',
    plugins: [react(), redirectStaleIndexToDevEntry],
    server: {
        // `server.open` is NOT automatically prefixed with `base` — it must
        // be the full path the browser should request.
        open: '/worldheat-tracker/app.html',
    },
    build: {
        rollupOptions: {
            input: fileURLToPath(new URL('./app.html', import.meta.url)),
        },
    },
});
